-- Drop Tables if they already exist to avoid conflicts
DROP TABLE IF EXISTS Enrollments;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS CourseSchedule;
DROP TABLE IF EXISTS Buildings;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Campuses;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Professors;
DROP TABLE IF EXISTS StudentStatuses;

-- Create Database
CREATE DATABASE IF NOT EXISTS UniversityCourses;
USE UniversityCourses;

-- Create StudentStatuses Table
CREATE TABLE StudentStatuses (
    StatusID INT PRIMARY KEY AUTO_INCREMENT,
    StatusName VARCHAR(20) NOT NULL
);

INSERT INTO StudentStatuses (StatusName) VALUES 
    ('Incoming'),
    ('Freshman'),
    ('Sophomore'),
    ('Junior'),
    ('Senior'),
    ('Alumni');

-- Create Professors Table
CREATE TABLE Professors (
    ProfessorID INT PRIMARY KEY AUTO_INCREMENT,
    ProfessorName VARCHAR(100) NOT NULL
);
INSERT INTO Professors (ProfessorName) VALUES
-- Insert unique professors into the Professors table
INSERT INTO Professors (ProfessorName) VALUES
    ('Abbott, Amy E.'),
    ('Adams, Ann-Marie'),
    ('Alvarez, Beda E.'),
    ('Amsden, Juli'),
    ('Angell, Eliot J.'),
    ('Aranda, Blanca'),
    ('Barnes, Emma M.'),
    ('Barnes, Mollie E.'),
    ('Barth, Sean M.'),
    ('Beachkofsky, Sarah L.'),
    ('Beall, Christina'),
    ('Becker, Shawn K.'),
    ('Berrios, Kayla C.'),
    ('Bessent, Laura M.'),
    ('Bond, Christopher'),
    ('Boniecki, Kelli'),
    ('Borgianini, Stephen A.'),
    ('Bowen, John R.'),
    ('Boyle, William P.'),
    ('Brandt, Kenneth C.'),
    ('Brockington, Djuanna M.'),
    ('Brooks, Gary T.'),
    ('Brugler, Mercer R.'),
    ('Burcin, Laura B.'),
    ('Caldwell, Jill E.'),
    ('Canada, Brian A.'),
    ('Capello, Rebecca K.'),
    ('Carey, Brian E.'),
    ('Catma, Serkan'),
    ('Cavanagh, Kimberly K.'),
    ('Cherry, David L.'),
    ('Ciresi, Lisa V.'),
    ('Cohan, Deborah J.'),
    ('Comitz, Paul H.'),
    ('Antonio, Edward L.'),
    ('Daugherty, Crystal'),
    ('Dawson, Audrey R.'),
    ('Dopf, Kevin C.'),
    ('Draud, Travis E.'),
    ('Dudas, Kimberly'),
    ('Duffy, James A.'),
    ('Edmunds, Morgan P.'),
    ('Erdei, Ronald'),
    ('Evans, Zachary C.'),
    ('Farrell, Carmen B.'),
    ('Farris, Amiri'),
    ('Ferrick, Cathleen P.'),
    ('Foss, Michael E.'),
    ('Fusi, Davide'),
    ('Gibson, Ian B.'),
    ('Gibson, Suzanne L.'),
    ('Gill, Diana'),
    ('Glassman, Tavis J.'),
    ('Golabek, Sue C.'),
    ('Griesse, James M.'),
    ('Guittar, Nicholas A.'),
    ('Haering, Samantha J.'),
    ('Hallisy, Beth H.'),
    ('Hammond, Elizabeth'),
    ('Hampson, Courtney E.'),
    ('Hardin, Jon-Michael'),
    ('Harris, Robert W.'),
    ('Heiens, Richard A.'),
    ('Henz, Thomas'),
    ('Higgins, Luke B.'),
    ('Hoffer, Lauren N.'),
    ('Hogenboom, Timothy J.'),
    ('Hollis, Meldon'),
    ('Holmes, Gloria G.'),
    ('Holt, Jan R.'),
    ('Hoy, Kathryn I.'),
    ('Huemme, Robert C.'),
    ('Huggins, Amy'),
    ('Hull, Sarah D.'),
    ('Hunnicutt, Melodie A.'),
    ('Hutchison, Lynne M.'),
    ('Ingram, Carole T.'),
    ('James, Timothy M.'),
    ('Johnson, Elizabeth L.'),
    ('Jones Williams, Morgin'),
    ('Jones, Amalia C.'),
    ('Jones, Jeffrey'),
    ('Kiernan, Katrina'),
    ('Kilgore, Robert E.'),
    ('Knapp, Sandra K.'),
    ('Knop, Brian'),
    ('Krebs, Salome L.'),
    ('Kuehn, Joanne'),
    ('Kunkle, Amy C.'),
    ('Lahar, Cindy J.'),
    ('Landrum, Robert H.'),
    ('Lawson, Alayne F.'),
    ('Layton, Shawn'),
    ('Leadem, John J.'),
    ('Leaphart, Amy E.'),
    ('Leblanc, Jeffrey D.'),
    ('Lefavi, Robert G.'),
    ('Lejeune, Danelle'),
    ('Lewis, Thomas E.'),
    ('Liang, Xuwei'),
    ('Logue, Lindsey N.'),
    ('Lovell, Laurie L.'),
    ('Madden, Kathryn R.'),
    ('Malphrus, P. Ellen'),
    ('Manor, Jalen M.'),
    ('Marlowe, Bruce A.'),
    ('Maxwell, Mary K.'),
    ('McClure, Ellen C.'),
    ('McCombs, Kelly L.'),
    ('McCoy, Erin'),
    ('McQuillen, Jeffrey P.'),
    ('Meriwether, Anna T.'),
    ('Messick, Kyle J.'),
    ('Mitra, Aditi'),
    ('Montie, Eric W.'),
    ('Morgan, Daniel'),
    ('Morris, Olivia S.'),
    ('Mundey, Peter J.'),
    ('Nadeau, Angela L.'),
    ('Nelson, Benjamin J.'),
    ('Connor, Teagan A.'),
    ('Osbaldiston, Richard J.'),
    ('Owen, Sarah'),
    ('Pate, George J.'),
    ('Pawelek, Lukasz D.'),
    ('Pedersen, Andrew'),
    ('Peery, Angela'),
    ('Petrucci, Joan M.'),
    ('Pettay, Daniel T.'),
    ('Ponce, Chelsea M.'),
    ('Poore, Daphne M.'),
    ('Powell, Alyssa B.'),
    ('Prestby, Kelly'),
    ('Ptacin, Anna C.'),
    ('Raley, Jessica A.'),
    ('Reibel, Melody D.'),
    ('Ricardo, Elizabeth'),
    ('Ritchie, Kimberly B.'),
    ('Rizzi, Mary C.'),
    ('Roberts, Summer C.'),
    ('Robinson, Dawn M.'),
    ('Runyan, Catherine F.'),
    ('Russell, Nadine'),
    ('Sams, Laurel A.'),
    ('Sanders, Manuel J.'),
    ('Sawyer, Caroline'),
    ('Seabrook, Michelene R.'),
    ('Sevim, Volkan'),
    ('Shinn, James M.'),
    ('Shroyer, Ashley R.'),
    ('Sidletsky, James'),
    ('Simon, Paul G.'),
    ('Skees, Murray W.'),
    ('Smith, Bradley A.'),
    ('Snoddy, Catherine'),
    ('Staton, Joseph L.'),
    ('Stuart, Aurel E.'),
    ('Sturgis, Cynthia L.'),
    ('Swift, Peter E.'),
    ('Swofford, Sarah C.'),
    ('Thomas, Najmah'),
    ('Thornton, Heather L.'),
    ('Thrasher, William J.'),
    ('Tompkins, Renarta H.'),
    ('Vaillancourt, Rose'),
    ('Vargo, Lori J.'),
    ('Villena-Alvarez, Juanita I.'),
    ('Violette, Jayne L.'),
    ('Weatherhead, Nora K.'),
    ('Webb, Emily M.'),
    ('Weir, Carol A.'),
    ('Whewell, Aubrey'),
    ('Willard, Jeremy'),
    ('Woods, Gabriel L.'),
    ('Wright, Brandon J.'),
    ('Zhang, Xiaomei'),
    ('Zientek, Patricia'),
    ('Zinn, David F.');


-- Create Subjects Table
CREATE TABLE Subjects (
    SubjectID INT PRIMARY KEY AUTO_INCREMENT,
    Subject VARCHAR(10) NOT NULL,
    SubjectDescription VARCHAR(255)
);

INSERT INTO Subjects (Subject, SubjectDescription) VALUES
    ('ACCT', 'Accounting'),
    ('AFAM', 'African American Studies'),
    ('ANTH', 'Anthropology'),
    ('ARTE', 'Art Education'),
    ('ARTH', 'Art History'),
    ('ARTS', 'Art Studio'),
    ('ASTR', 'Astronomy'),
    ('BADM', 'Business Administration'),
    ('BIOL', 'Biology'),
    ('CHEM', 'Chemistry'),
    ('COMM', 'Communications'),
    ('CPLT', 'Comparative Literature'),
    ('CSCI', 'Computer Science'),
    ('CSXE', 'Computer Science Extension'),
    ('ECON', 'Economics'),
    ('EDCI', 'Education Instruction'),
    ('EDEC', 'Early Childhood Education'),
    ('EDEL', 'Elementary Education'),
    ('EDEX', 'Special Education'),
    ('EDFO', 'Foundations of Education'),
    ('EDME', 'Mathematics Education'),
    ('EDPH', 'Physical Education'),
    ('EDPY', 'Educational Psychology'),
    ('EDRD', 'Reading Education'),
    ('EDRM', 'Educational Research'),
    ('ENGL', 'English'),
    ('ENGR', 'Engineering'),
    ('ENTR', 'Entrepreneurship'),
    ('FREN', 'French'),
    ('GEOG', 'Geography'),
    ('GERM', 'German'),
    ('GLST', 'Global Studies'),
    ('HIST', 'History'),
    ('HMSV', 'Human Services'),
    ('HONS', 'Honors College'),
    ('HPRO', 'Health Promotion'),
    ('HRTM', 'Hospitality and Tourism Management'),
    ('IDST', 'Interdisciplinary Studies'),
    ('INTL', 'International Studies'),
    ('ISAT', 'Information Systems and Technology'),
    ('LANG', 'Languages'),
    ('LBST', 'Liberal Studies'),
    ('LING', 'Linguistics'),
    ('MART', 'Media Arts'),
    ('MATH', 'Mathematics'),
    ('MGMT', 'Management'),
    ('MGSC', 'Management Science'),
    ('MKTG', 'Marketing'),
    ('MSCI', 'Military Science'),
    ('MUSC', 'Music'),
    ('NURS', 'Nursing'),
    ('PEDU', 'Physical Education'),
    ('PHIL', 'Philosophy'),
    ('PHYS', 'Physics'),
    ('POLI', 'Political Science'),
    ('PSYC', 'Psychology'),
    ('PUBH', 'Public Health'),
    ('RELG', 'Religion'),
    ('SOCY', 'Sociology'),
    ('SPAN', 'Spanish'),
    ('SPRT', 'Sports Management'),
    ('STAT', 'Statistics'),
    ('THEA', 'Theatre'),
    ('UNIV', 'University Studies'),
    ('USC', 'University of South Carolina');

-- Create Campuses Table
CREATE TABLE Campuses (
    CampusID INT PRIMARY KEY AUTO_INCREMENT,
    CampusName VARCHAR(100) NOT NULL,
    Address VARCHAR(255) NOT NULL
);
INSERT INTO Campuses (CampusName, Address) VALUES
    ('Bluffton Campus', '1 University Blvd., Bluffton, SC 29909'),
    ('Beaufort Campus', '801 Carteret Street, Beaufort, SC 29902'),
    ('Hilton Head Island Campus', '1 Sand Shark Drive, Hilton Head Island, SC 29928');

-- Create Buildings table
CREATE TABLE Buildings (
    BuildingID INT PRIMARY KEY AUTO_INCREMENT,
    CampusID INT,
    BuildingCode VARCHAR(10),
    BuildingName VARCHAR(255),
    FOREIGN KEY (CampusID) REFERENCES Campuses(CampusID)
);

INSERT INTO Buildings (CampusID, BuildingCode, BuildingName) VALUES
    (1, 'CMPCCTR', 'Campus Center'),
    (1, 'HARG', 'Hargray Building'),
    (1, 'LIBR2', 'Library Building'),
    (1, 'RECCTR', 'Recreation Center'),
    (1, 'SCITEC', 'Science & Technology Building'),
    (2, 'ARTS', 'Art Studio'),
    (2, 'CFA', 'Center for the Arts'),
    (2, 'MSCI', 'Marine Science Building'),
    (2, 'NWCSTL', 'New Castle Building'),
    (2, 'VAD', 'Visual Arts & Design Building'),
    (2, '1100BO', '1100 Boundary Street'),
    (3, 'HHHC', 'Hilton Head Hospitality Center');

-- Create Courses Table
CREATE TABLE Courses (
    CourseID INT PRIMARY KEY AUTO_INCREMENT,
    SubjectID INT,
    CourseNumber VARCHAR(10) NOT NULL,
    CourseName VARCHAR(255) NOT NULL,
    FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
);

INSERT INTO Courses (SubjectID, CourseName, CourseNumber) 
VALUES 
	/* COMPUTER SCIENCE */
	('13', 'Introduction to Computer Concepts', 'B101'), 
	('13', 'Introduction to HTML and CSS', 'B102'),  
	('13', 'Computer Programming Techniques, Practices, and Tools', 'B104'),  
	('13', 'Object-Oriented Programming I', 'B145'), 
	('13', 'Object-Oriented Programming II', 'B146'),  
	('13', 'Introduction to Computational Science', 'B150'),  
	('13', 'Introduction to Computer Security', 'B201'),  
	('13', 'Introduction to Front-End Web Development', 'B202'), 
	('13', 'Computer System Administration', 'B207'),  
	('13', 'Special Topics in Computer Programming', 'B209'),  
	('13', 'Digital Logic Design', 'B211'),  
	('13', 'Introduction to Computer Architecture', 'B212'), 
	('13', 'Introduction to Software Engineering', 'B240'),  
	('13', 'Mobile Application Development', 'B250'),  
	('13', 'Introduction to Computational Biology', 'B255'),  
	('13', 'Graphics, Multimedia and User-Interface Design', 'B265'), 
	('13', 'Computational Mathematics', 'B280'),  
	('13', 'Introduction to Digital Forensics', 'B317'),  
	('13', 'Database Systems Management', 'B320'),  
	('13', 'Database-Driven Applications Development', 'B321'), 
	('13', 'Introduction to Data Structures and Algorithms', 'B350'),  
	('13', 'Operating Systems', 'B360'),  
	('13', 'Computer Graphics', 'B365'),  
	('13', 'Independent Study', 'B399'),  
	('13', 'Information Security Principles', 'B401'),  
	('13', 'Selected Topics in Computing', 'B409'),  
	('13', 'Introduction to Computer Networks', 'B416'), 
	('13', 'Mathematical Modeling', 'B419'),  
	('13', 'Database Management Systems II', 'B420'),  
	('13', 'Introduction to Data Mining', 'B422'),  
	('13', 'Special Topics in Computer Networks and Distributed Computing', 'B426'),  
	('13', 'Information Technology Project Management', 'B437'),  
	('13', 'Modeling and Simulation', 'B450'),  
	('13', 'Computer Game Development', 'B452'), 
	('13', 'Introduction to Digital Image Processing', 'B463'),  
	('13', 'Data Visualization', 'B466'),  
	('13', 'High Performance Computing', 'B469'),  
	('13', 'Software Testing and Verification', 'B470'),  
	('13', 'Computational Science Co-op/Internship', 'B499'),  
	('13', 'Practical Computing for Computational Scientists', 'B500'),  
	('13', 'Advanced Statistical Methods', 'B501'), 
	('13', 'Numerical Analysis and Computing', 'B502'),  
	('13', 'Topics in Computational Science', 'B515'),  
	('13', 'Data Communications and Networks', 'B516'), 
	('13', 'Advanced Topics in Database Systems', 'B520'),  
	('13', 'Data Mining', 'B522'),  
	('13', 'Systems Modeling and Simulation', 'B550'),  
	('13', 'Digital Image Processing', 'B563'), 
	('13', 'Data Visualization', 'B566'),  
	('13', 'High Performance Computing', 'B569'),  
	('13', 'Software System Design and Implementation', 'B570'),  
	('13', 'Independent Study', 'B599'),  
	('13', 'Principles of Computer Security', 'B601'),  
	('13', 'Data Management and Analytics', 'B622'),  
	('13', 'Industrial or Research Internship', 'B699'), 
	('13', 'Research Project', 'B797'),  
	('13', 'Master''s Thesis', 'B799'),
	/* INFORMATION SYSTEMS AND TECHNOLOGY */
	('40', 'Introduction to HTML and CSS', 'B102'),  
	('40', 'Computer Programming Techniques, Practices, and Tools', 'B104'),  
	('40', 'Object-Oriented Programming I', 'B145'), 
	('40', 'Object-Oriented Programming II', 'B146'),  
	('40', 'Introduction to Computational Science', 'B150'),  
	('40', 'Introduction to Computer Security', 'B201'),  
	('40', 'Introduction to Front-End Web Development', 'B202'), 
	('40', 'Computer System Administration', 'B207'),  
	('40', 'Digital Logic Design', 'B211'),  
	('40', 'Introduction to Computer Architecture', 'B212'), 
	('40', 'Introduction to Software Engineering', 'B240'),  
	('40', 'Mobile Application Development', 'B250'),  
	('40', 'Introduction to Computational Biology', 'B255'),  
	('40', 'Graphics, Multimedia and User-Interface Design', 'B265'), 
	('40', 'Computational Mathematics', 'B280'),  
	('40', 'Introduction to Digital Forensics', 'B317'),  
	('40', 'Ethical Hacking', 'B318'), 
	('40', 'Database Systems Management', 'B320'),  
	('40', 'Database-Driven Applications Development', 'B321'), 
	('40', 'Introduction to Data Structures and Algorithms', 'B350'),  
	('40', 'Computer Graphics', 'B365'),  
	('40', 'Independent Study', 'B399'),  
	('40', 'Information Security Principles', 'B401'),  
	('40', 'Special Topics in Security', 'B409'),  
	('40', 'Introduction to Computer Networks', 'B416'), 
	('40', 'Database Management Systems II', 'B420'),  
	('40', 'Introduction to Data Mining', 'B422'),  
	('40', 'Special Topics in Computer Networks and Distributed Computing', 'B426'),  
	('40', 'Information Technology Project Management', 'B437'),  
	('40', 'Modeling and Simulation', 'B450'),  
	('40', 'Cryptography', 'B455'), 
	('40', 'High Performance Computing', 'B469'),  
	('40', 'Software System Process & Management', 'B470'),  
	('40', 'Computer Science Co-op/Internship', 'B499'),
    /* PSYCHOLOGY */
    ('56', 'Introduction to Psychology', 'B101'),
    ('56', 'Research Methods in Psychology', 'B200'),
    ('56', 'Statistics Lab in Psychology', 'B201'),
    ('56', 'Psychological Statistics', 'B202'),
    ('56', 'Laboratory in Psychology', 'B203'),
    ('56', 'Human Growth and Development', 'B209'),
    ('56', 'Psychology of Adjustment', 'B210'),
    ('56', 'Applied Psychology', 'B212'),
    ('56', 'Human Sexual Behavior', 'B214'),
    ('56', 'Psychology of Marriage', 'B216'),
    ('56', 'Psychology of Women', 'B218'),
    ('56', 'Psychology of Religion', 'B220'),
    ('56', 'Industrial/Organizational Psychology', 'B224'),
    ('56', 'Sport Psychology', 'B229'),
    ('56', 'Learning and Memory', 'B302'),
    ('56', 'Principles of Gerontology', 'B303'),
    ('56', 'Abnormal Psychology', 'B311'),
    ('56', 'Abnormal Behavior in Children', 'B312'),
    ('56', 'Life Span Developmental Psychology', 'B321'),
    ('56', 'Psychology of Child Development', 'B322'),
    ('56', 'Psychology of Adolescence', 'B324'),
    ('56', 'Psychology of Early and Middle Adulthood', 'B326'),
    ('56', 'Psychology of Aging', 'B328'),
    ('56', 'Social Psychology', 'B331'),
    ('56', 'Personality Theory', 'B341'),
    ('56', 'Biological Psychology', 'B361'),
    ('56', 'Cultural Psychology', 'B380'),
    ('56', 'Independent Study', 'B399'),
    ('56', 'Cognitive Psychology', 'B401'),
    ('56', 'Working with Older Adults', 'B403'),
    ('56', 'Psychology Consumer Behavior', 'B404'),
    ('56', 'History and Systems of Psychology', 'B406'),
    ('56', 'Positive Psychology', 'B409'),
    ('56', 'Introduction to Clinical Psychology', 'B411'),
    ('56', 'Trauma & Recovery', 'B413'),
    ('56', 'Community Psychology', 'B415'),
    ('56', 'Psychology of Drug Use and Effects', 'B418'),
    ('56', 'Psychology and the Legal System', 'B425'),
    ('56', 'Psychological Tests and Measurement', 'B441'),
    ('56', 'Sensation and Perception', 'B451'),
    ('56', 'Psychology in Film', 'B462'),
    ('56', 'Health Psychology', 'B465'),
    ('56', 'Selected Topics in Psychology', 'B490'),
    ('56', 'Advanced Research Methods in Psychology', 'B494'),
    ('56', 'Internship in Psychology I', 'B495'),
    ('56', 'Internship in Psychology II', 'B496'),
    ('56', 'Advanced Independent Study', 'B498'),
    ('56', 'Individual Research', 'B499');

-- Create Rooms Table
CREATE TABLE Rooms (
    RoomID INT PRIMARY KEY AUTO_INCREMENT,
    CampusID INT,
    Building VARCHAR(10),  -- References BuildingCode in Buildings table
    Room VARCHAR(10),
    FOREIGN KEY (CampusID) REFERENCES Campuses(CampusID),
    FOREIGN KEY (Building) REFERENCES Buildings(BuildingCode)
);

INSERT INTO Rooms (CampusID, Building, Room) VALUES
    -- Bluffton Campus (CampusID = 1)
    (1, 'CMPCCTR', '106A'),
    (1, 'CMPCCTR', '105'),
    (1, 'HARG', '270'),
    (1, 'LIBR2', '207'),
    (1, 'LIBR2', '213'),
    (1, 'RECCTR', '118'),
    (1, 'RECCTR', '114'),
    (1, 'RECCTR', '222'),
    (1, 'RECCTR', '260'),
    (1, 'SCITEC', '102'),
    
    -- Beaufort Campus (CampusID = 2)
    (2, 'ARTS', '101'),
    (2, 'CFA', '102'),
    (2, 'MSCI', '104'),
    (2, 'NWCSTL', '200'),
    (2, 'VAD', '112'),
    (2, '1100BO', '1'),
    (2, '1100BO', '111'),
    (2, 'NWCSTL', '205'),
    
    -- Hilton Head Island Campus (CampusID = 3)
    (3, 'HHHC', '207'),
    (3, 'HHHC', '213'),
    (3, 'HHHC', '102'),
    (3, 'HHHC', '202'),
    (3, 'HHHC', '302');

-- Create Course Schedule Table
CREATE TABLE CourseSchedule (
    ScheduleID INT PRIMARY KEY AUTO_INCREMENT,
    CRN VARCHAR(20) NOT NULL,
    CourseID INT,
    ProfessorID INT,
    RoomID INT,
    AcademicPeriodDesc VARCHAR(50),
    Days VARCHAR(20),
    Time VARCHAR(50),
    MaxEnrollment INT,
    ActualEnrolled INT,
    MeetingTypeDesc VARCHAR(50),
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID),
    FOREIGN KEY (ProfessorID) REFERENCES Professors(ProfessorID),
    FOREIGN KEY (RoomID) REFERENCES Rooms(RoomID)
);

-- Create Students Table with StatusID as foreign key
CREATE TABLE Students (
    StudentID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    Major VARCHAR(100),
    EnrollmentYear INT,
    StatusID INT,
    FOREIGN KEY (StatusID) REFERENCES StudentStatuses(StatusID)
);

INSERT INTO Students (FirstName, LastName, Email, Major, EnrollmentYear, StatusID) VALUES
    /* INCOMING */
    -- CSCI
    ('Aiden Blackwell','aiden.blackwell@example.com','CSCI',2025,1),
    ('Emma Greenfield','emma.greenfield@example.com','CSCI',2025,1),
    ('Jacob Whitaker','jacob.whitaker@example.com','CSCI',2025,1),
    ('Olivia Patel','olivia.patel@example.com','CSCI',2025,1),
    ('Ethan Raj','ethan.raj@example.com','CSCI',2025,1),
    ('Sophia Gutierrez','sophia.gutierrez@example.com','CSCI',2025,1),
    ('William Nguyen','william.nguyen@example.com','CSCI',2025,1),
    ('Isabella Hernandez','isabella.hernandez@example.com','CSCI',2025,1),
    ('Lucas Flores','lucas.flores@example.com','CSCI',2025,1),
    ('Ava Diaz','ava.diaz@example.com','CSCI',2025,1),
    -- ISAT
    ('Liam Morales','liam.morales@example.com','ISAT',2025,1),
    ('Mia Duarte','mia.duarte@example.com','ISAT',2025,1),
    ('Noah Reyes','noah.reyes@example.com','ISAT',2025,1),
    ('Isabella Rosales','isabella.rosales@example.com','ISAT',2025,1),
    ('Daniel Quintana','daniel.quintana@example.com','ISAT',2025,1),
    ('Emma Campos','emma.campos@example.com','ISAT',2025,1),
    ('Sebastian Ortiz','sebastian.ortiz@example.com','ISAT',2025,1),
    ('Olivia Mendoza','olivia.mendoza@example.com','ISAT',2025,1),
    ('Mateo Vargas','mateo.vargas@example.com','ISAT',2025,1),
    ('Ava Santana','ava.santana@example.com','ISAT',2025,1),
    --PSYC
    ('Michael Guerrero','michael.guerrero@example.com','PSYC',2025,1),
    ('Emily Ramirez','emily.ramirez@example.com','PSYC',2025,1),
    ('Alexander Jimenez','alexander.jimenez@example.com','PSYC',2025,1),
    ('Isabella Castillo','isabella.castillo@example.com','PSYC',2025,1),
    ('Joshua Alvarez','joshua.alvarez@example.com','PSYC',2025,1),

    /* FRESHMEN */
    -- CSCI
    ('David Romero','david.romero@example.com','CSCI',2024,2),
    ('Avery Gutierrez','avery.gutierrez@example.com','CSCI',2024,2),
    ('Owen Reyes','owen.reyes@example.com','CSCI',2024,2),
    ('Aubrey Mendoza','aubrey.mendoza@example.com','CSCI',2024,2),
    ('Ethan Santana','ethan.santana@example.com','CSCI',2024,2),
    -- ISAT
    ('Sophia Vargas','sophia.vargas@example.com','ISAT',2024,2),
    ('Logan Diaz','logan.diaz@example.com','ISAT',2024,2),
    ('Isabella Morales','isabella.morales@example.com','ISAT',2024,2),
    ('Mason Duarte','mason.duarte@example.com','ISAT',2024,2),
    ('Abigail Rosales','abigail.rosales@example.com','ISAT',2024,2),
    --PSYC
    ('Jacob Campos','jacob.campos@example.com','PSYC',2024,2),
    ('Emma Ortiz','emma.ortiz@example.com','PSYC',2024,2),
    ('William Quintana','william.quintana@example.com','PSYC',2024,2),
    ('Mia Alvarez','mia.alvarez@example.com','PSYC',2024,2),
    ('Lucas Castillo','lucas.castillo@example.com','PSYC',2024,2),

    /* SOPHOMORES */
    -- CSCI
    ('Liam Flores','liam.flores@example.com','CSCI',2023,3),
    ('Ava Patel','ava.patel@example.com','CSCI',2023,3),
    ('Noah Raj','noah.raj@example.com','CSCI',2023,3),
    ('Isabella Whitaker','isabella.whitaker@example.com','CSCI',2023,3),
    ('Ethan Greenfield','ethan.greenfield@example.com','CSCI',2023,3),
    -- ISAT
    ('Olivia Blackwell','olivia.blackwell@example.com','ISAT',2023,3),
    ('Alexander Nguyen','alexander.nguyen@example.com','ISAT',2023,3),
    ('Mia Hernandez','mia.hernandez@example.com','ISAT',2023,3),
    ('Michael Gutierrez','michael.gutierrez@example.com','ISAT',2023,3),
    ('Emily Diaz','emily.diaz@example.com','ISAT',2023,3),
    --PSYC
    ('Emma Guerrero','emma.guerrero@example.com','PSYC',2023,3),
    ('Joshua Ramirez','joshua.ramirez@example.com','PSYC',2023,3),
    ('Avery Jimenez','avery.jimenez@example.com','PSYC',2023,3),
    ('Owen Castillo','owen.castillo@example.com','PSYC',2023,3),
    ('Aubrey Alvarez','aubrey.alvarez@example.com','PSYC',2023,3),

    /* JUNIORS */
    -- CSCI
    ('Daniel Morales','daniel.morales@example.com','CSCI',2022,4),
    ('Sophia Duarte','sophia.duarte@example.com','CSCI',2022,4),
    ('Sebastian Reyes','sebastian.reyes@example.com','CSCI',2022,4),
    ('Abigail Rosales','abigail.rosales@example.com','CSCI',2022,4),
    ('Logan Vargas','logan.vargas@example.com','CSCI',2022,4),
    -- ISAT
    ('Mason Campos','mason.campos@example.com','ISAT',2022,4),
    ('Isabella Ortiz','isabella.ortiz@example.com','ISAT',2022,4),
    ('Jacob Quintana','jacob.quintana@example.com','ISAT',2022,4),
    ('Mia Mendoza','mia.mendoza@example.com','ISAT',2022,4),
    ('William Santana','william.santana@example.com','ISAT',2022,4),
    --PSYC
    ('Liam Guerrero','liam.guerrero@example.com','PSYC',2022,4),
    ('Ava Ramirez','ava.ramirez@example.com','PSYC',2022,4),
    ('Noah Jimenez','noah.jimenez@example.com','PSYC',2022,4),
    ('Isabella Castillo','isabella.castillo@example.com','PSYC',2022,4),
    ('Ethan Alvarez','ethan.alvarez@example.com','PSYC',2022,4),

    /* SENIORS */
    -- CSCI
    ('Olivia Romero','olivia.romero@example.com','CSCI',2021,5),
    ('Alexander Gutierrez','alexander.gutierrez@example.com','CSCI',2021,5),
    ('Mia Reyes','mia.reyes@example.com','CSCI',2021,5),
    ('Michael Mendoza','michael.mendoza@example.com','CSCI',2021,5),
    ('Emily Santana','emily.santana@example.com','CSCI',2021,5),
    -- ISAT
    ('Joshua Vargas','joshua.vargas@example.com','ISAT',2021,5),
    ('Avery Diaz','avery.diaz@example.com','ISAT',2021,5),
    ('Owen Morales','owen.morales@example.com','ISAT',2021,5),
    ('Aubrey Duarte','aubrey.duarte@example.com','ISAT',2021,5),
    ('David Rosales','david.rosales@example.com','ISAT',2021,5),
    --PSYC
    ('Emma Campos','emma.campos@example.com','PSYC',2021,5),
    ('Jacob Ortiz','jacob.ortiz@example.com','PSYC',2021,5),
    ('Sophia Quintana','sophia.quintana@example.com','PSYC',2021,5),
    ('Liam Alvarez','liam.alvarez@example.com','PSYC',2021,5),
    ('Ava Castillo','ava.castillo@example.com','PSYC',2021,5),

    /* ALUMNI */
    -- CSCI
    ('Noah Ramirez','noah.ramirez@example.com','CSCI',2020,6),
    ('Isabella Jimenez','isabella.jimenez@example.com','CSCI',2019,6),
    ('Ethan Guerrero','ethan.guerrero@example.com','CSCI',2018,6),
    ('Olivia Flores','olivia.flores@example.com','CSCI',2017,6),
    ('Alexander Patel','alexander.patel@example.com','CSCI',2016,6),
    -- ISAT
    ('Mia Raj','mia.raj@example.com','ISAT',2020,6),
    ('Michael Whitaker','michael.whitaker@example.com','ISAT',2019,6),
    ('Emily Greenfield','emily.greenfield@example.com','ISAT',2018,6),
    ('Joshua Blackwell','joshua.blackwell@example.com','ISAT',2017,6),
    ('Avery Nguyen','avery.nguyen@example.com','ISAT',2016,6),
    --PSYC
    ('Owen Hernandez','owen.hernandez@example.com','PSYC',2020,6),
    ('Aubrey Gutierrez','aubrey.gutierrez@example.com','PSYC',2019,6),
    ('David Diaz','david.diaz@example.com','PSYC',2018,6),
    ('Emma Campos','emma.campos@example.com','PSYC',2017,6),
    ('Jacob Morales','jacob.morales@example.com','PSYC',2016,6)


-- Create Enrollments Table
CREATE TABLE Enrollments (
    EnrollmentID INT PRIMARY KEY AUTO_INCREMENT,
    StudentID INT,
    ScheduleID INT,
    EnrollmentDate DATE,
    Grade VARCHAR(5),
    FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
    FOREIGN KEY (ScheduleID) REFERENCES CourseSchedule(ScheduleID)
);