INSERT INTO StudentStatuses (StatusName) VALUES 
    ('Incoming'),
    ('Freshman'),
    ('Sophomore'),
    ('Junior'),
    ('Senior'),
    ('Alumni');

INSERT INTO Professors (ProfessorName) VALUES
    ('Abbott, Amy E.'),
    ('Adams, Ann-Marie'),
    ('Alvarez, Beda E.'),
    ('Amsden, Juli'),
    ('Angell, Eliot J.'),
    ('Aranda, Blanca'),
    ('Barnes, Emma M.'),
    ('Barnes, Mollie E.'),
    ('Barth, Sean M.'),
    ('Beachkofsky, Sarah L.'),
    ('Beall, Christina'),
    ('Becker, Shawn K.'),
    ('Berrios, Kayla C.'),
    ('Bessent, Laura M.'),
    ('Bond, Christopher'),
    ('Boniecki, Kelli'),
    ('Borgianini, Stephen A.'),
    ('Bowen, John R.'),
    ('Boyle, William P.'),
    ('Brandt, Kenneth C.'),
    ('Brockington, Djuanna M.'),
    ('Brooks, Gary T.'),
    ('Brugler, Mercer R.'),
    ('Burcin, Laura B.'),
    ('Caldwell, Jill E.'),
    ('Canada, Brian A.'),
    ('Capello, Rebecca K.'),
    ('Carey, Brian E.'),
    ('Catma, Serkan'),
    ('Cavanagh, Kimberly K.'),
    ('Cherry, David L.'),
    ('Ciresi, Lisa V.'),
    ('Cohan, Deborah J.'),
    ('Comitz, Paul H.'),
    ('Antonio, Edward L.'),
    ('Daugherty, Crystal'),
    ('Dawson, Audrey R.'),
    ('Dopf, Kevin C.'),
    ('Draud, Travis E.'),
    ('Dudas, Kimberly'),
    ('Duffy, James A.'),
    ('Edmunds, Morgan P.'),
    ('Erdei, Ronald'),
    ('Evans, Zachary C.'),
    ('Farrell, Carmen B.'),
    ('Farris, Amiri'),
    ('Ferrick, Cathleen P.'),
    ('Foss, Michael E.'),
    ('Fusi, Davide'),
    ('Gibson, Ian B.'),
    ('Gibson, Suzanne L.'),
    ('Gill, Diana'),
    ('Glassman, Tavis J.'),
    ('Golabek, Sue C.'),
    ('Griesse, James M.'),
    ('Guittar, Nicholas A.'),
    ('Haering, Samantha J.'),
    ('Hallisy, Beth H.'),
    ('Hammond, Elizabeth'),
    ('Hampson, Courtney E.'),
    ('Hardin, Jon-Michael'),
    ('Harris, Robert W.'),
    ('Heiens, Richard A.'),
    ('Henz, Thomas'),
    ('Higgins, Luke B.'),
    ('Hoffer, Lauren N.'),
    ('Hogenboom, Timothy J.'),
    ('Hollis, Meldon'),
    ('Holmes, Gloria G.'),
    ('Holt, Jan R.'),
    ('Hoy, Kathryn I.'),
    ('Huemme, Robert C.'),
    ('Huggins, Amy'),
    ('Hull, Sarah D.'),
    ('Hunnicutt, Melodie A.'),
    ('Hutchison, Lynne M.'),
    ('Ingram, Carole T.'),
    ('James, Timothy M.'),
    ('Johnson, Elizabeth L.'),
    ('Jones Williams, Morgin'),
    ('Jones, Amalia C.'),
    ('Jones, Jeffrey'),
    ('Kiernan, Katrina'),
    ('Kilgore, Robert E.'),
    ('Knapp, Sandra K.'),
    ('Knop, Brian'),
    ('Krebs, Salome L.'),
    ('Kuehn, Joanne'),
    ('Kunkle, Amy C.'),
    ('Lahar, Cindy J.'),
    ('Landrum, Robert H.'),
    ('Lawson, Alayne F.'),
    ('Layton, Shawn'),
    ('Leadem, John J.'),
    ('Leaphart, Amy E.'),
    ('Leblanc, Jeffrey D.'),
    ('Lefavi, Robert G.'),
    ('Lejeune, Danelle'),
    ('Lewis, Thomas E.'),
    ('Liang, Xuwei'),
    ('Logue, Lindsey N.'),
    ('Lovell, Laurie L.'),
    ('Madden, Kathryn R.'),
    ('Malphrus, P. Ellen'),
    ('Manor, Jalen M.'),
    ('Marlowe, Bruce A.'),
    ('Maxwell, Mary K.'),
    ('McClure, Ellen C.'),
    ('McCombs, Kelly L.'),
    ('McCoy, Erin'),
    ('McQuillen, Jeffrey P.'),
    ('Meriwether, Anna T.'),
    ('Messick, Kyle J.'),
    ('Mitra, Aditi'),
    ('Montie, Eric W.'),
    ('Morgan, Daniel'),
    ('Morris, Olivia S.'),
    ('Mundey, Peter J.'),
    ('Nadeau, Angela L.'),
    ('Nelson, Benjamin J.'),
    ('Connor, Teagan A.'),
    ('Osbaldiston, Richard J.'),
    ('Owen, Sarah'),
    ('Pate, George J.'),
    ('Pawelek, Lukasz D.'),
    ('Pedersen, Andrew'),
    ('Peery, Angela'),
    ('Petrucci, Joan M.'),
    ('Pettay, Daniel T.'),
    ('Ponce, Chelsea M.'),
    ('Poore, Daphne M.'),
    ('Powell, Alyssa B.'),
    ('Prestby, Kelly'),
    ('Ptacin, Anna C.'),
    ('Raley, Jessica A.'),
    ('Reibel, Melody D.'),
    ('Ricardo, Elizabeth'),
    ('Ritchie, Kimberly B.'),
    ('Rizzi, Mary C.'),
    ('Roberts, Summer C.'),
    ('Robinson, Dawn M.'),
    ('Runyan, Catherine F.'),
    ('Russell, Nadine'),
    ('Sams, Laurel A.'),
    ('Sanders, Manuel J.'),
    ('Sawyer, Caroline'),
    ('Seabrook, Michelene R.'),
    ('Sevim, Volkan'),
    ('Shinn, James M.'),
    ('Shroyer, Ashley R.'),
    ('Sidletsky, James'),
    ('Simon, Paul G.'),
    ('Skees, Murray W.'),
    ('Smith, Bradley A.'),
    ('Snoddy, Catherine'),
    ('Staton, Joseph L.'),
    ('Stuart, Aurel E.'),
    ('Sturgis, Cynthia L.'),
    ('Swift, Peter E.'),
    ('Swofford, Sarah C.'),
    ('Thomas, Najmah'),
    ('Thornton, Heather L.'),
    ('Thrasher, William J.'),
    ('Tompkins, Renarta H.'),
    ('Vaillancourt, Rose'),
    ('Vargo, Lori J.'),
    ('Villena-Alvarez, Juanita I.'),
    ('Violette, Jayne L.'),
    ('Weatherhead, Nora K.'),
    ('Webb, Emily M.'),
    ('Weir, Carol A.'),
    ('Whewell, Aubrey'),
    ('Willard, Jeremy'),
    ('Woods, Gabriel L.'),
    ('Wright, Brandon J.'),
    ('Zhang, Xiaomei'),
    ('Zientek, Patricia'),
    ('Zinn, David F.');

INSERT INTO Subjects (Subject, SubjectDescription) VALUES
    ('ACCT', 'Accounting'),
    ('AFAM', 'African American Studies'),
    ('ANTH', 'Anthropology'),
    ('ARTE', 'Art Education'),
    ('ARTH', 'Art History'),
    ('ARTS', 'Art Studio'),
    ('ASTR', 'Astronomy'),
    ('BADM', 'Business Administration'),
    ('BIOL', 'Biology'),
    ('CHEM', 'Chemistry'),
    ('COMM', 'Communications'),
    ('CPLT', 'Comparative Literature'),
    ('CSCI', 'Computer Science'),
    ('CSXE', 'Computer Science Extension'),
    ('ECON', 'Economics'),
    ('EDCI', 'Education Instruction'),
    ('EDEC', 'Early Childhood Education'),
    ('EDEL', 'Elementary Education'),
    ('EDEX', 'Special Education'),
    ('EDFO', 'Foundations of Education'),
    ('EDME', 'Mathematics Education'),
    ('EDPH', 'Physical Education'),
    ('EDPY', 'Educational Psychology'),
    ('EDRD', 'Reading Education'),
    ('EDRM', 'Educational Research'),
    ('ENGL', 'English'),
    ('ENGR', 'Engineering'),
    ('ENTR', 'Entrepreneurship'),
    ('FREN', 'French'),
    ('GEOG', 'Geography'),
    ('GERM', 'German'),
    ('GLST', 'Global Studies'),
    ('HIST', 'History'),
    ('HMSV', 'Human Services'),
    ('HONS', 'Honors College'),
    ('HPRO', 'Health Promotion'),
    ('HRTM', 'Hospitality and Tourism Management'),
    ('IDST', 'Interdisciplinary Studies'),
    ('INTL', 'International Studies'),
    ('ISAT', 'Information Systems and Technology'),
    ('LANG', 'Languages'),
    ('LBST', 'Liberal Studies'),
    ('LING', 'Linguistics'),
    ('MART', 'Media Arts'),
    ('MATH', 'Mathematics'),
    ('MGMT', 'Management'),
    ('MGSC', 'Management Science'),
    ('MKTG', 'Marketing'),
    ('MSCI', 'Military Science'),
    ('MUSC', 'Music'),
    ('NURS', 'Nursing'),
    ('PEDU', 'Physical Education'),
    ('PHIL', 'Philosophy'),
    ('PHYS', 'Physics'),
    ('POLI', 'Political Science'),
    ('PSYC', 'Psychology'),
    ('PUBH', 'Public Health'),
    ('RELG', 'Religion'),
    ('SOCY', 'Sociology'),
    ('SPAN', 'Spanish'),
    ('SPRT', 'Sports Management'),
    ('STAT', 'Statistics'),
    ('THEA', 'Theatre'),
    ('UNIV', 'University Studies'),
    ('USC', 'University of South Carolina');

INSERT INTO Campuses (CampusName, Address) VALUES
    ('Bluffton Campus', '1 University Blvd., Bluffton, SC 29909'),
    ('Beaufort Campus', '801 Carteret Street, Beaufort, SC 29902'),
    ('Hilton Head Island Campus', '1 Sand Shark Drive, Hilton Head Island, SC 29928');

INSERT INTO Buildings (CampusID, BuildingCode, BuildingName) VALUES
    (1, 'CMPCCTR', 'Campus Center'),
    (1, 'HARG', 'Hargray Building'),
    (1, 'LIBR2', 'Library Building'),
    (1, 'RECCTR', 'Recreation Center'),
    (1, 'SCITEC', 'Science & Technology Building'),
    (2, 'ARTS', 'Art Studio'),
    (2, 'CFA', 'Center for the Arts'),
    (2, 'MSCI', 'Marine Science Building'),
    (2, 'NWCSTL', 'New Castle Building'),
    (2, 'VAD', 'Visual Arts & Design Building'),
    (2, '1100BO', '1100 Boundary Street'),
    (3, 'HHHC', 'Hilton Head Hospitality Center');

INSERT INTO Courses (SubjectID, CourseName, CourseNumber) VALUES
    /* GEN EDS */
    ('26', 'Composition & Rhetoric', 'B101'), 
    ('13', 'Introduction to Computer Concepts', 'B101'), 
    ('13', 'Introduction to Computer Concepts', 'B101'), 
    ('13', 'Introduction to Computer Concepts', 'B101'), 
    ('13', 'Introduction to Computer Concepts', 'B101'), 
    ('13', 'Introduction to Computer Concepts', 'B101'), 
    ('13', 'Introduction to Computer Concepts', 'B101'), 
	/* COMPUTER SCIENCE */
	('13', 'Introduction to Computer Concepts', 'B101'), 
	('13', 'Introduction to HTML and CSS', 'B102'),  
	('13', 'Computer Programming Techniques, Practices, and Tools', 'B104'),  
	('13', 'Object-Oriented Programming I', 'B145'), 
	('13', 'Object-Oriented Programming II', 'B146'),  
	('13', 'Introduction to Computational Science', 'B150'),  
	('13', 'Introduction to Computer Security', 'B201'),  
	('13', 'Introduction to Front-End Web Development', 'B202'), 
	('13', 'Computer System Administration', 'B207'),  
	('13', 'Special Topics in Computer Programming', 'B209'),  
	('13', 'Digital Logic Design', 'B211'),  
	('13', 'Introduction to Computer Architecture', 'B212'), 
	('13', 'Introduction to Software Engineering', 'B240'),  
	('13', 'Mobile Application Development', 'B250'),  
	('13', 'Introduction to Computational Biology', 'B255'),  
	('13', 'Graphics, Multimedia and User-Interface Design', 'B265'), 
	('13', 'Computational Mathematics', 'B280'),  
	('13', 'Introduction to Digital Forensics', 'B317'),  
	('13', 'Database Systems Management', 'B320'),  
	('13', 'Database-Driven Applications Development', 'B321'), 
	('13', 'Introduction to Data Structures and Algorithms', 'B350'),  
	('13', 'Operating Systems', 'B360'),  
	('13', 'Computer Graphics', 'B365'),  
	('13', 'Independent Study', 'B399'),  
	('13', 'Information Security Principles', 'B401'),  
	('13', 'Selected Topics in Computing', 'B409'),  
	('13', 'Introduction to Computer Networks', 'B416'), 
	('13', 'Mathematical Modeling', 'B419'),  
	('13', 'Database Management Systems II', 'B420'),  
	('13', 'Introduction to Data Mining', 'B422'),  
	('13', 'Special Topics in Computer Networks and Distributed Computing', 'B426'),  
	('13', 'Information Technology Project Management', 'B437'),  
	('13', 'Modeling and Simulation', 'B450'),  
	('13', 'Computer Game Development', 'B452'), 
	('13', 'Introduction to Digital Image Processing', 'B463'),  
	('13', 'Data Visualization', 'B466'),  
	('13', 'High Performance Computing', 'B469'),  
	('13', 'Software Testing and Verification', 'B470'),  
	('13', 'Computational Science Co-op/Internship', 'B499'),  
	('13', 'Practical Computing for Computational Scientists', 'B500'),  
	('13', 'Advanced Statistical Methods', 'B501'), 
	('13', 'Numerical Analysis and Computing', 'B502'),  
	('13', 'Topics in Computational Science', 'B515'),  
	('13', 'Data Communications and Networks', 'B516'), 
	('13', 'Advanced Topics in Database Systems', 'B520'),  
	('13', 'Data Mining', 'B522'),  
	('13', 'Systems Modeling and Simulation', 'B550'),  
	('13', 'Digital Image Processing', 'B563'), 
	('13', 'Data Visualization', 'B566'),  
	('13', 'High Performance Computing', 'B569'),  
	('13', 'Software System Design and Implementation', 'B570'),  
	('13', 'Independent Study', 'B599'),  
	('13', 'Principles of Computer Security', 'B601'),  
	('13', 'Data Management and Analytics', 'B622'),  
	('13', 'Industrial or Research Internship', 'B699'), 
	('13', 'Research Project', 'B797'),  
	('13', 'Master''s Thesis', 'B799'),
	/* INFORMATION SYSTEMS AND TECHNOLOGY */
	('40', 'Introduction to HTML and CSS', 'B102'),  
	('40', 'Computer Programming Techniques, Practices, and Tools', 'B104'),  
	('40', 'Object-Oriented Programming I', 'B145'), 
	('40', 'Object-Oriented Programming II', 'B146'),  
	('40', 'Introduction to Computational Science', 'B150'),  
	('40', 'Introduction to Computer Security', 'B201'),  
	('40', 'Introduction to Front-End Web Development', 'B202'), 
	('40', 'Computer System Administration', 'B207'),  
	('40', 'Digital Logic Design', 'B211'),  
	('40', 'Introduction to Computer Architecture', 'B212'), 
	('40', 'Introduction to Software Engineering', 'B240'),  
	('40', 'Mobile Application Development', 'B250'),  
	('40', 'Introduction to Computational Biology', 'B255'),  
	('40', 'Graphics, Multimedia and User-Interface Design', 'B265'), 
	('40', 'Computational Mathematics', 'B280'),  
	('40', 'Introduction to Digital Forensics', 'B317'),  
	('40', 'Ethical Hacking', 'B318'), 
	('40', 'Database Systems Management', 'B320'),  
	('40', 'Database-Driven Applications Development', 'B321'), 
	('40', 'Introduction to Data Structures and Algorithms', 'B350'),  
	('40', 'Computer Graphics', 'B365'),  
	('40', 'Independent Study', 'B399'),  
	('40', 'Information Security Principles', 'B401'),  
	('40', 'Special Topics in Security', 'B409'),  
	('40', 'Introduction to Computer Networks', 'B416'), 
	('40', 'Database Management Systems II', 'B420'),  
	('40', 'Introduction to Data Mining', 'B422'),  
	('40', 'Special Topics in Computer Networks and Distributed Computing', 'B426'),  
	('40', 'Information Technology Project Management', 'B437'),  
	('40', 'Modeling and Simulation', 'B450'),  
	('40', 'Cryptography', 'B455'), 
	('40', 'High Performance Computing', 'B469'),  
	('40', 'Software System Process & Management', 'B470'),  
	('40', 'Computer Science Co-op/Internship', 'B499'),
    /* PSYCHOLOGY */
    ('56', 'Introduction to Psychology', 'B101'),
    ('56', 'Research Methods in Psychology', 'B200'),
    ('56', 'Statistics Lab in Psychology', 'B201'),
    ('56', 'Psychological Statistics', 'B202'),
    ('56', 'Laboratory in Psychology', 'B203'),
    ('56', 'Human Growth and Development', 'B209'),
    ('56', 'Psychology of Adjustment', 'B210'),
    ('56', 'Applied Psychology', 'B212'),
    ('56', 'Human Sexual Behavior', 'B214'),
    ('56', 'Psychology of Marriage', 'B216'),
    ('56', 'Psychology of Women', 'B218'),
    ('56', 'Psychology of Religion', 'B220'),
    ('56', 'Industrial/Organizational Psychology', 'B224'),
    ('56', 'Sport Psychology', 'B229'),
    ('56', 'Learning and Memory', 'B302'),
    ('56', 'Principles of Gerontology', 'B303'),
    ('56', 'Abnormal Psychology', 'B311'),
    ('56', 'Abnormal Behavior in Children', 'B312'),
    ('56', 'Life Span Developmental Psychology', 'B321'),
    ('56', 'Psychology of Child Development', 'B322'),
    ('56', 'Psychology of Adolescence', 'B324'),
    ('56', 'Psychology of Early and Middle Adulthood', 'B326'),
    ('56', 'Psychology of Aging', 'B328'),
    ('56', 'Social Psychology', 'B331'),
    ('56', 'Personality Theory', 'B341'),
    ('56', 'Biological Psychology', 'B361'),
    ('56', 'Cultural Psychology', 'B380'),
    ('56', 'Independent Study', 'B399'),
    ('56', 'Cognitive Psychology', 'B401'),
    ('56', 'Working with Older Adults', 'B403'),
    ('56', 'Psychology Consumer Behavior', 'B404'),
    ('56', 'History and Systems of Psychology', 'B406'),
    ('56', 'Positive Psychology', 'B409'),
    ('56', 'Introduction to Clinical Psychology', 'B411'),
    ('56', 'Trauma & Recovery', 'B413'),
    ('56', 'Community Psychology', 'B415'),
    ('56', 'Psychology of Drug Use and Effects', 'B418'),
    ('56', 'Psychology and the Legal System', 'B425'),
    ('56', 'Psychological Tests and Measurement', 'B441'),
    ('56', 'Sensation and Perception', 'B451'),
    ('56', 'Psychology in Film', 'B462'),
    ('56', 'Health Psychology', 'B465'),
    ('56', 'Selected Topics in Psychology', 'B490'),
    ('56', 'Advanced Research Methods in Psychology', 'B494'),
    ('56', 'Internship in Psychology I', 'B495'),
    ('56', 'Internship in Psychology II', 'B496'),
    ('56', 'Advanced Independent Study', 'B498'),
    ('56', 'Individual Research', 'B499');

INSERT INTO Rooms (CampusID, Building, Room) VALUES
    -- Bluffton Campus (CampusID = 1)
    (1, 'CMPCCTR', '106A'),
    (1, 'CMPCCTR', '105'),
    (1, 'HARG', '270'),
    (1, 'LIBR2', '207'),
    (1, 'LIBR2', '213'),
    (1, 'RECCTR', '118'),
    (1, 'RECCTR', '114'),
    (1, 'RECCTR', '222'),
    (1, 'RECCTR', '260'),
    (1, 'SCITEC', '102'),
    
    -- Beaufort Campus (CampusID = 2)
    (2, 'ARTS', '101'),
    (2, 'CFA', '102'),
    (2, 'MSCI', '104'),
    (2, 'NWCSTL', '200'),
    (2, 'VAD', '112'),
    (2, '1100BO', '1'),
    (2, '1100BO', '111'),
    (2, 'NWCSTL', '205'),
    
    -- Hilton Head Island Campus (CampusID = 3)
    (3, 'HHHC', '207'),
    (3, 'HHHC', '213'),
    (3, 'HHHC', '102'),
    (3, 'HHHC', '202'),
    (3, 'HHHC', '302');

INSERT INTO CourseSchedule (ProfessorID, CourseID, RoomID, CRN, AcademicPeriodDesc, Days, Time, MaxEnrollment, ActualEnrolled, MeetingTypeDesc) VALUES 
	/* COMPUTER SCIENCE */
	(1, 1, 1, '10101', 'Fall 2021', 'MWF', '10:00 AM - 10:50 AM', 30, 30, 'Lecture'),
    (2, 2, 2, '10102', 'Fall 2021', 'MWF', '11:00 AM - 11:50 AM', 30, 30, 'Lecture'),
    (3, 3, 3, '10103', 'Fall 2021', 'MWF', '12:00 PM - 12:50 PM', 30, 30, 'Lecture'),
    (4, 4, 4, '10104', 'Fall 2021', 'MWF', '1:00 PM - 1:50 PM', 30, 30, 'Lecture'),
    (5, 5, 5, '10105', 'Fall 2021', 'MWF', '2:00 PM - 2:50 PM', 30, 30, 'Lecture'),
    (6, 6, 6, '10106', 'Fall 2021', 'MWF', '3:00 PM - 3:50 PM', 30, 30, 'Lecture'),
    (7, 7, 7, '10107', 'Fall 2021', 'MWF', '4:00 PM - 4:50 PM', 30, 30, 'Lecture'),
    (8, 8, 8, '10108', 'Fall 2021', 'MWF', '5:00 PM - 5:50 PM', 30, 30, 'Lecture'),
    (9, 9, 9, '10109', 'Fall 2021', 'MWF', '6:00 PM - 6:50 PM', 30, 30, 'Lecture'),
    (10, 10, 10, '10110', 'Fall 2021', 'MWF', '7:00 PM - 7:50 PM', 30, 30, 'Lecture'),

INSERT INTO Students (FirstName, LastName, Email, Major, EnrollmentYear, StatusID) VALUES
    /* INCOMING */
    -- CSCI
    ('Aiden', 'Morgan','amorgan@email.uscb.edu','CSCI',2025,1),
    ('Emma', 'Young','eyoung@email.uscb.edu','CSCI',2025,1),
    ('Jacob', 'Holland','jholland@email.uscb.edu','CSCI',2025,1),
    ('Olivia', 'Blake','oblake@email.uscb.edu','CSCI',2025,1),
    ('Ethan', 'Brooks','ebrooks@email.uscb.edu','CSCI',2025,1),
    ('Sophia', 'Tran','stran@email.uscb.edu','CSCI',2025,1),
    ('William', 'Liu','wliu@email.uscb.edu','CSCI',2025,1),
    ('Isabella', 'Shah','ishah@email.uscb.edu','CSCI',2025,1),
    ('Lucas', 'Yoon','lyoon@email.uscb.edu','CSCI',2025,1),
    ('Ava', 'Chen','achen@email.uscb.edu','CSCI',2025,1),
    -- ISAT
    ('Liam', 'Carter','lcarter@email.uscb.edu','ISAT',2025,1),
    ('Mia', 'Baker','mbaker@email.uscb.edu','ISAT',2025,1),
    ('Noah', 'King','nking@email.uscb.edu','ISAT',2025,1),
    ('Isabella', 'Choi','ichoi@email.uscb.edu','ISAT',2025,1),
    ('Daniel', 'Singh','dsingh@email.uscb.edu','ISAT',2025,1),
    ('Emma', 'Kumar','ekumar@email.uscb.edu','ISAT',2025,1),
    ('Sebastian', 'Ortiz','sortiz@email.uscb.edu','ISAT',2025,1),
    ('Olivia', 'Navarro','onavarro@email.uscb.edu','ISAT',2025,1),
    ('Mateo', 'Pham','mpham@email.uscb.edu','ISAT',2025,1),
    ('Ava', 'Ali','aali@email.uscb.edu','ISAT',2025,1),
    -- PSYC
    ('Michael', 'Kim','mkim@email.uscb.edu','PSYC',2025,1),
    ('Emily', 'Peters','epeters@email.uscb.edu','PSYC',2025,1),
    ('Alexander', 'Lopez','alopez@email.uscb.edu','PSYC',2025,1),
    ('Isabella', 'Rao','irao@email.uscb.edu','PSYC',2025,1),
    ('Joshua', 'Park','jpark@email.uscb.edu','PSYC',2025,1),

    /* FRESHMEN */
    -- CSCI
    ('David', 'Nguyen','dnguyen@email.uscb.edu','CSCI',2024,2),
    ('Avery', 'Patel','apatel@email.uscb.edu','CSCI',2024,2),
    ('Owen', 'Sullivan','osullivan@email.uscb.edu','CSCI',2024,2),
    ('Aubrey', 'Greene','agreene@email.uscb.edu','CSCI',2024,2),
    ('Ethan', 'Foster','efoster@email.uscb.edu','CSCI',2024,2),
    ('Liam', 'Dixon','ldixon@email.uscb.edu','CSCI',2024,2),
    ('Ava', 'Vargas','avargas@email.uscb.edu','CSCI',2024,2),
    ('Noah', 'Larsen','nlarsen@email.uscb.edu','CSCI',2024,2),
    ('Isabella', 'Chavez','ichavez@email.uscb.edu','CSCI',2024,2),
    ('Ethan', 'Hoffman','ehoffman@email.uscb.edu','CSCI',2024,2),
    -- ISAT
    ('Sophia', 'Moreno','smoreno@email.uscb.edu','ISAT',2024,2),
    ('Logan', 'Silva','lsilva@email.uscb.edu','ISAT',2024,2),
    ('Isabella', 'Rivera','irivera@email.uscb.edu','ISAT',2024,2),
    ('Mason', 'Cruz','mcruz@email.uscb.edu','ISAT',2024,2),
    ('Abigail', 'Flores','aflores@email.uscb.edu','ISAT',2024,2),
    ('Olivia', 'Torres','otorres@email.uscb.edu','ISAT',2024,2),
    ('Alexander', 'Gomez','agomez@email.uscb.edu','ISAT',2024,2),
    ('Mia', 'Ruiz','mruiz@email.uscb.edu','ISAT',2024,2),
    ('Michael', 'Delgado','mdelgado@email.uscb.edu','ISAT',2024,2),
    ('Emily', 'Sanders','esanders@email.uscb.edu','ISAT',2024,2),
    -- PSYC
    ('Jacob', 'Webb','jwebb@email.uscb.edu','PSYC',2024,2),
    ('Emma', 'Garcia','egarcia@email.uscb.edu','PSYC',2024,2),
    ('William', 'Beck','wbeck@email.uscb.edu','PSYC',2024,2),
    ('Mia', 'Turner','mturner@email.uscb.edu','PSYC',2024,2),
    ('Lucas', 'Graham','lgraham@email.uscb.edu','PSYC',2024,2),

    /* SOPHOMORES */
    -- CSCI
    ('Daniel', 'Kim','dkim@email.uscb.edu','CSCI',2023,3),
    ('Sophia', 'Stone','sstone@email.uscb.edu','CSCI',2023,3),
    ('Sebastian', 'Cross','scross@email.uscb.edu','CSCI',2023,3),
    ('Abigail', 'Hayes','ahayes@email.uscb.edu','CSCI',2023,3),
    ('Logan', 'Reed','lreed@email.uscb.edu','CSCI',2023,3),
    ('Emily', 'Castro','ecastro@email.uscb.edu','CSCI',2023,3),
    ('James', 'Daniels','jdaniels@email.uscb.edu','CSCI',2023,3),
    ('Avery', 'Fisher','afisher@email.uscb.edu','CSCI',2023,3),
    ('Grace', 'Simmons','gsimmons@email.uscb.edu','CSCI',2023,3),
    ('Henry', 'Patterson','hpatterson@email.uscb.edu','CSCI',2023,3),
    -- ISAT
    ('Sophia', 'Morales','smorales@email.uscb.edu','ISAT',2023,3),
    ('Benjamin', 'Harper','bharper@email.uscb.edu','ISAT',2023,3),
    ('Mason', 'Reyes','mreyes@email.uscb.edu','ISAT',2023,3),
    ('Ella', 'Armstrong','earmstrong@email.uscb.edu','ISAT',2023,3),
    ('Oliver', 'Gutierrez','ogutierrez@email.uscb.edu','ISAT',2023,3),
    ('Ethan', 'Caldwell','ecaldwell@email.uscb.edu','ISAT',2023,3),
    ('Amelia', 'Ramirez','aramirez@email.uscb.edu','ISAT',2023,3),
    ('Logan', 'Bowman','lbowman@email.uscb.edu','ISAT',2023,3),
    ('Aria', 'Kennedy','akennedy@email.uscb.edu','ISAT',2023,3),
    ('Evan', 'Bates','ebates@email.uscb.edu','ISAT',2023,3),
    -- PSYC
    ('Emma', 'Moss','emoss@email.uscb.edu','PSYC',2023,3),
    ('Joshua', 'Cook','jcook@email.uscb.edu','PSYC',2023,3),
    ('Avery', 'Adams','aadams@email.uscb.edu','PSYC',2023,3),
    ('Owen', 'Russell','orussell@email.uscb.edu','PSYC',2023,3),
    ('Aubrey', 'Bryant','abryant@email.uscb.edu','PSYC',2023,3),

    /* JUNIORS */
    -- CSCI
    ('Olivia', 'Stevens','ostevens@email.uscb.edu','CSCI',2022,4),
    ('Alexander', 'Evans','aevans@email.uscb.edu','CSCI',2022,4),
    ('Mia', 'Carter','mcarter@email.uscb.edu','CSCI',2022,4),
    ('Michael', 'Peterson','mpeterson@email.uscb.edu','CSCI',2022,4),
    ('Emily', 'Long','elong@email.uscb.edu','CSCI',2022,4),
    ('David', 'Phillips','dphillips@email.uscb.edu','CSCI',2022,4),
    ('Sofia', 'Ross','sross@email.uscb.edu','CSCI',2022,4),
    ('Lucas', 'Harrison','lharrison@email.uscb.edu','CSCI',2022,4),
    ('Lily', 'Bryant','lbryant@email.uscb.edu','CSCI',2022,4),
    ('Ryan', 'Ford','rford@email.uscb.edu','CSCI',2022,4),
    -- ISAT
    ('Mason', 'Ward','mward@email.uscb.edu','ISAT',2022,4),
    ('Lily', 'Griffith','lgriffith@email.uscb.edu','ISAT',2022,4),
    ('Jacob', 'Ellis','jellis@email.uscb.edu','ISAT',2022,4),
    ('Emma', 'Ferguson','eferguson@email.uscb.edu','ISAT',2022,4),
    ('Logan', 'Garrett','lgarrett@email.uscb.edu','ISAT',2022,4),
    ('Isabella', 'Price','iprice@email.uscb.edu','ISAT',2022,4),
    ('Ethan', 'Jacobs','ejacobs@email.uscb.edu','ISAT',2022,4),
    ('Benjamin', 'Barnes','bbarnes@email.uscb.edu','ISAT',2022,4),
    ('Alexander', 'Schmidt','aschmidt@email.uscb.edu','ISAT',2022,4),
    ('Sophia', 'Richards','srichards@email.uscb.edu','ISAT',2022,4),
    -- PSYC
    ('Jacob', 'Sanchez','jsanchez@email.uscb.edu','PSYC',2022,4),
    ('Abigail', 'Torres','atorres@email.uscb.edu','PSYC',2022,4),
    ('Lucas', 'Scott','lscott@email.uscb.edu','PSYC',2022,4),
    ('Sophia', 'Howard','showard@email.uscb.edu','PSYC',2022,4),
    ('Mia', 'Coleman','mcoleman@email.uscb.edu','PSYC',2022,4),

    /* SENIORS */
    -- CSCI
    ('Nathan', 'Morgan','nmorgan@email.uscb.edu','CSCI',2021,5),
    ('Amelia', 'Butler','abutler@email.uscb.edu','CSCI',2021,5),
    ('Isaac', 'Cox','icox@email.uscb.edu','CSCI',2021,5),
    ('Charlotte', 'Diaz','cdiaz@email.uscb.edu','CSCI',2021,5),
    ('Grace', 'Rogers','grogers@email.uscb.edu','CSCI',2021,5),
    ('Gabriel', 'Jordan','gjordan@email.uscb.edu','CSCI',2021,5),
    ('Ella', 'Perry','eperry@email.uscb.edu','CSCI',2021,5),
    ('Henry', 'Jenkins','hjenkins@email.uscb.edu','CSCI',2021,5),
    ('Sebastian', 'Fleming','sfleming@email.uscb.edu','CSCI',2021,5),
    ('Scarlett', 'Dean','sdean@email.uscb.edu','CSCI',2021,5),
    -- ISAT
    ('Mila', 'Henderson','mhenderson@email.uscb.edu','ISAT',2021,5),
    ('Zoe', 'Nash','znash@email.uscb.edu','ISAT',2021,5),
    ('Julian', 'Reid','jreid@email.uscb.edu','ISAT',2021,5),
    ('Ellie', 'Owens','eowens@email.uscb.edu','ISAT',2021,5),
    ('Levi', 'Mendoza','lmendoza@email.uscb.edu','ISAT',2021,5),
    ('Violet', 'Fox','vfox@email.uscb.edu','ISAT',2021,5),
    ('Jack', 'Gray','jgray@email.uscb.edu','ISAT',2021,5),
    ('Maya', 'Hughes','mhughes@email.uscb.edu','ISAT',2021,5),
    ('Liam', 'Watson','lwatson@email.uscb.edu','ISAT',2021,5),
    ('Lily', 'Bishop','lbishop@email.uscb.edu','ISAT',2021,5),
    -- PSYC
    ('Aubrey', 'Sutton','asutton@email.uscb.edu','PSYC',2021,5),
    ('Daniel', 'Wade','dwade@email.uscb.edu','PSYC',2021,5),
    ('Evelyn', 'Shaw','eshaw@email.uscb.edu','PSYC',2021,5),
    ('Isaiah', 'Rich','irich@email.uscb.edu','PSYC',2021,5),
    ('Sophia', 'Fowler','sfowler@email.uscb.edu','PSYC',2021,5),

    /* ALUMNI */
    -- CSCI
    ('Benjamin', 'Walker','bwalker@email.uscb.edu','CSCI',2020,6),
    ('Ava', 'Rogers','arogers@email.uscb.edu','CSCI',2020,6),
    ('Henry', 'Long','hlong@email.uscb.edu','CSCI',2019,6),
    ('Olivia', 'Mitchell','omitchell@email.uscb.edu','CSCI',2019,6),
    ('Liam', 'Brooks','lbrooks@email.uscb.edu','CSCI',2018,6),
    ('Emily', 'Howard','ehoward@email.uscb.edu','CSCI',2018,6),
    ('Noah', 'Foster','nfoster@email.uscb.edu','CSCI',2017,6),
    ('Sophia', 'Reed','sreed@email.uscb.edu','CSCI',2017,6),
    ('James', 'Clark','jclark@email.uscb.edu','CSCI',2016,6),
    ('Mia', 'Ramos','mramos@email.uscb.edu','CSCI',2016,6),
    -- ISAT
    ('Ethan', 'Murphy','emurphy@email.uscb.edu','ISAT',2020,6),
    ('Lily', 'Price','lprice@email.uscb.edu','ISAT',2020,6),
    ('Alexander', 'Jenkins','ajenkins@email.uscb.edu','ISAT',2019,6),
    ('Ella', 'Barnes','ebarnes@email.uscb.edu','ISAT',2019,6),
    ('Jackson', 'Sanders','jsanders@email.uscb.edu','ISAT',2018,6),
    ('Avery', 'Wright','awright@email.uscb.edu','ISAT',2018,6),
    ('Grace', 'Cook','gcook@email.uscb.edu','ISAT',2017,6),
    ('Mason', 'Bell','mbell@email.uscb.edu','ISAT',2017,6),
    ('Emily', 'Gray','egray@email.uscb.edu','ISAT',2016,6),
    ('Lucas', 'Hayes','lhayes@email.uscb.edu','ISAT',2016,6),
    -- PSYC
    ('Sofia', 'Henderson','shenderson@email.uscb.edu','PSYC',2020,6),
    ('Ryan', 'Bennett','rbennett@email.uscb.edu','PSYC',2019,6),
    ('Zoe', 'Simpson','zsimpson@email.uscb.edu','PSYC',2018,6),
    ('Joe', 'Harkman','jharkman@email.uscb.edu','PSYC',2017,6),
    ('Aiden', 'Rivera','arivera@email.uscb.edu','PSYC',2016,6);