INSERT INTO Subjects (SubjectID, Subject, SubjectDescription) VALUES
    (1, 'ACCT', 'Accounting'),
    (2, 'AFAM', 'African American Studies'),
    (3, 'ANTH', 'Anthropology'),
    (4, 'ARTE', 'Art Education'),
    (5, 'ARTH', 'Art History'),
    (6, 'ARTS', 'Art Studio'),
    (7, 'ASTR', 'Astronomy'),
    (8, 'BADM', 'Business Administration'),
    (9, 'BIOL', 'Biology'),
    (10, 'CHEM', 'Chemistry'),
    (11, 'COMM', 'Communications'),
    (12, 'CPLT', 'Comparative Literature'),
    (13, 'CSCI', 'Computer Science'),
    (14, 'CSXE', 'Computer Science Extension'),
    (15, 'ECON', 'Economics'),
    (16, 'EDCI', 'Education Instruction'),
    (17, 'EDEC', 'Early Childhood Education'),
    (18, 'EDEL', 'Elementary Education'),
    (19, 'EDEX', 'Special Education'),
    (20, 'EDFO', 'Foundations of Education'),
    (21, 'EDME', 'Mathematics Education'),
    (22, 'EDPH', 'Physical Education'),
    (23, 'EDPY', 'Educational Psychology'),
    (24, 'EDRH', 'Reading Education'),
    (25, 'EDRM', 'Educational Research'),
    (26, 'ENGL', 'English'),
    (27, 'ENGR', 'Engineering'),
    (28, 'ENTR', 'Entrepreneurship'),
    (29, 'FREN', 'French'),
    (30, 'GEOG', 'Geography'),
    (31, 'GERM', 'German'),
    (32, 'GLST', 'Global Studies'),
    (33, 'HIST', 'History'),
    (34, 'HMSV', 'Human Services'),
    (35, 'HONS', 'Honors College'),
    (36, 'HPRO', 'Health Promotion'),
    (37, 'HRTM', 'Hospitality and Tourism Management'),
    (38, 'IDST', 'Interdisciplinary Studies'),
    (39, 'INTL', 'International Studies'),
    (40, 'ISAT', 'Information Systems and Technology'),
    (41, 'LANG', 'Languages'),
    (42, 'LBST', 'Liberal Studies'),
    (43, 'LING', 'Linguistics'),
    (44, 'MART', 'Media Arts'),
    (45, 'MATH', 'Mathematics'),
    (46, 'MGMT', 'Management'),
    (47, 'MGSC', 'Management Science'),
    (48, 'MKTG', 'Marketing'),
    (49, 'MSCI', 'Marine Science'),
    (50, 'MUSC', 'Music'),
    (51, 'NURS', 'Nursing'),
    (52, 'PEDU', 'Physical Education'),
    (53, 'PHIL', 'Philosophy'),
    (54, 'PHYS', 'Physics'),
    (55, 'POLI', 'Political Science'),
    (56, 'PSYC', 'Psychology'),
    (57, 'PUBH', 'Public Health'),
    (58, 'RELG', 'Religion'),
    (59, 'SOCY', 'Sociology'),
    (60, 'SPAN', 'Spanish'),
    (61, 'SPRT', 'Sports Management'),
    (62, 'STAT', 'Statistics'),
    (63, 'THEA', 'Theatre'),
    (64, 'UNIV', 'University Studies'),
    (65, 'USC', 'University of South Carolina');